version: "3"
services:
  front:
    build: ./front
    image: ertad-production-front:latest
    container_name: ertad-production-front
    restart: always
    ports:
      - "80:80"
    depends_on:
      - back
  back:
    build: ./back
    image: ertad-production-back:latest
    container_name: ertad-production-back
    restart: always
    ports:
      - "8080:3500"
